= Contact

Bonjour,

Je suis Nicolas Fédou, développeur back Java et coach technique.
J'aime l'informatique depuis que je compose des commandes avec Linux. Assembler des commandes, des objets, des composants, des pipelines, c'est comme jouer aux Légo pour moi.
Depuis mes premières mission, j'ai toujours cherché à améliorer les conditions de travail de l'équipe par des petits script, puis de la CI/CD et depuis quelques années avec de la montée en compétence sur les pratiques de développement agile.

Je travaille généralement avec des entreprises dont le logiciel est victime de son succès et commence à perdre en productivité ou en fiabilité.
Je leur permet de reprendre le contrôle sur leur patrimoine logiciel et d'avoir des développeurs qui maitrisent un savoir faire proche de l'état de l'art.
Le bénéfice principal étant de retrouver un logiciel capable d'évoluer à la vitesse du business du client sans défaut et qu'on ne décommissionne pas.

J'interviens souvent avec un rôle de développeur mentor, co-Tech Lead ou encore en coaching technique parfois même pour déployer les préconisations d'un audit réalisé par moi-même ou par un pair.
Je réalise parfois des diagnostiques facturés au temps passé pour résoudre un problème rapide.
