= PermaSoft

Pour des logiciels qui évoluent en harmonie avec votre business.

Pendant que votre business pivote, s'adapte et grandit, les logiciels à succès ont tendances à grossir.
Les nouvelles fonctionnalités s'intègrent dans une base de code existante qui décrit une version passée de votre business.
Il faut une bonne maîtrise du développement logiciel pour éviter que la version suivante de votre logiciel n'ai pas marques de votre business passé.
Les marques qui ne sont pas retirées, adaptées devront être maintenue, ajoutant une complexité inutile à votre logiciel jusqu'à xref:obesiciel.adoc[devenir un obésiciel].

PermaSoft vous accompagne dans le maintien de vos logiciels dans de
xref:maintenabilite.adoc[bonnes conditions de maintenabilité] et de xref:productivite.adoc[productivité de vos projets informatiques].

PermaSoft est l'entreprise unipersonnelle de Nicolas Fédou, développeur, coach technique, conseiller en IT spécialisé dans le craftsmanship et la maintenabilité des logiciels.

Le nom de PermaSoft est inspiré de celui de la PermaCulture qui est une contraction de "permanent culture".
La PermaCulture identifie et utilise les forces naturelles pour construire son projet (jardin, agriculture, etc.)
Cela permet de minimiser ses actions d'une part et d'avoir des effets produits par l'environnement, sans effort de notre part.
Cela demande plus de réflexion et moins d'actions pour un résultat équivalent.
On ne va se mentir, nous n'arrêterons pas nos efforts à un résultat équivalent.
Nous ferons la même quantité d'efforts dans tous les cas, nous irons simplement plus loin.
Je ne suis pas fans xref:metaphores.adoc[des métaphores de nos métiers], elles forcément trompeuses.
Je ne vous décrirais donc seulement xref:permaculture.adoc[ce que j'apprécie de la PermaCulture] sans essayer de vous faire passer une petite fleur pour un logiciel.

Ma vision de l'agilité
La stratégie pour être difficilement copiable, donc sortir de la survie en urgence et autre optimisation opérationnelle et enfin investir dans le long terme sereinement.

Audit de code suivi d'accompagnement à leur mise en place
Conseils en architecture logicielle (pas en infra cloud) suivi d'accompagnement à leur mise en place
Coaching technique
Co Tech Lead, Co CTO
Développement back Java Sénior avec un rôle modèle

Katas books
