= Métaphores

Les métaphores de notre métier avec les bâtisseurs, les chirurgiens, les artisans ou les jardiniers ont des limites de validité que seul les développeurs peuvent identifiés.
L'auditoire qui n'est pas du métier va appliquer la métaphore complète sur notre métier sans connaitre les limites d'invalidité...
Ils se construiront donc des idées erronées de notre métier.

La seule manière de décrire notre métier est de parler de notre métier.
Il n'y a pas de raccourcis.
Nous devons décrire le comportement d'une machine selon plusieurs critères:

1. De manière formelle et exhaustive pour qu'elle réalise les tâches dont nous avons besoin. (Kiss - Keep It Simple Small, Yagni, 3 rules of simple design)
1. De manière imagée pour que le développeur qui maintient le code comprenne l'intention du développeur d'origine. (Clean Code, Domain Driven Design)
1. De manière structurée donc bien rangée pour que les développeurs suivants puissent retrouver les détails à maintenir dans une motte de fonctionnalités utiles. (Software Architecture, Clean Architecture)
1. De manière justifiée pour que le développeur suivant puisse être sûr que la nouvelle fonctionnalité est un ajout où une modification d'un comportement existant et ainsi retirer en confiance le code devenu obsolète pour ne plus le maintenir. (Clean Tests, Behaviour Driven Development)

Ainsi le code est *LA métaphore* du produit.
Le logiciel à des entrées/sorties qui lui permettent d'interagir avec le monde (clavier, souris, réseau, écrans, disque dur, api tierces) de manière numérique.
Le code va donc réaliser une activité numérique qui remplacera ou aurait pu être une activité physique.
Nous vivons dans un monde physique et nos "entrées/sorties" sont nos sens et notre corps.
Nous imaginons le comportement du logiciel depuis notre monde physique.
Le logiciel ne perçois que le monde numérique.
Nous expliquons aux machines le comportement qu'elle doivent avoir à l'aide de code qui adapte notre contexte physique à son contexte numérique.
Ce code du logiciel est une métaphore, une représentation numérique limité de l'activité physique, nécessaire et suffisante pour que le logiciel ai les effets attendus.

