= Offres de services

//Les prix sont indicatifs d'une valeur apportée.
//La valeur d'une mission ne se limite pas à sa facturation en euros.

== 1. Audit de Code
* Interviews sur votre contexte et ce qui vous pose problème, les symptômes
* Souvent étude du métier, de l'espace du problème à résoudre
* Interview des acteurs ayant étudié le problème
* Interview des acteurs ayant construit la solution
* Etude de la solution
* Préconisations sur l'analyse du problème et/ou sur la solution
* Parfois proposition d'accompagnement sur le déploiement de certaines préconisations.

== 2. Accompagnements
* Soit par contrat de coaching
** Application d'un contrat de coaching tri-partite (commanditaire, coachés, coach) défini par un contexte, un problème, des besoins et une demande à satisfaire
** En intervention à la journée ou demi-journée
* Soit par lot d'heures de support

== 3. Développeur Craft
* Mise en place d'outils permettant de meilleures pratiques de développement
** Tests de fonctionnalités unitaires et d'intégration en boite blanche
** Outils de maintiens de l'architecture logicielle, de respect des conventions
* Rôle Modèle
** Co-Tech Lead sur le partage de bonnes pratiques de développement et leur mise en place
** Architecte Logiciel pour aller vers des services de tailles raisonnables (micro ou non), de la clean architecture et du KISS (Keep It Simple, Small - NDLR : je préfère Small)
** Développeur volontaire (sur la mise en place de pratiques de développement et tenant les délais de livraison de fonctionnalités métier)
